### ISSUE TITLE
MemRefBoundsIndexCapture error when converting custom fraud model

### ISSUE THREAD

**Issue by cjvolzka** [onnx/onnx-mlir#1280] opened 2022-03-29 15:36 UTC
We're getting an error trying to compile the following model [jan_improved.onnx.zip](https://github.com/onnx/onnx-mlir/files/8372936/jan_improved.onnx.zip) using onnx-mlir commit 35352d126b2af14e40858e7ddfb984a7e6cc53aa. We get the same error if we try and compile for CPU or NNPA, however NNPA is the desired goal.

At a glance, I didn't notice any unsupported Ops. The model was converted using tf2onnx 1.9.3. When I look at it using Netron I don't see anything strange (ie no dynamic loop ops).

```
onnx-mlir --O3 --EmitLib --mtriple=s390x-ibm-loz --mcpu=z14 jan_improved.onnx  -o CPU/jan_improved.onnx-mlir-preview-llvm -v
dlc: /DLCpp/third_party/onnx-mlir/src/Dialect/ONNX/IndexExpr.cpp:1646: mlir::IndexExpr mlir::MemRefBoundsIndexCapture::get(uint64_t) [with INDEX = mlir::DimIndexExpr; uint64_t = long unsigned int]: Assertion `i < memRank && "index out of bound"' failed.
```

**Comment by etiotto** [comment] 2022-03-29 21:13
The compiler assert during shape inference on the `onnx.Concat` operator that feeds the first LSTM operator. The issue is the value of the `axis` attribute for that Concat operator, the value of axis is `33554432`:

```
% onnx-mlir jan_improved.onnx --EmitONNXBasic ; grep "onnx.Concat" jan_improved.onnx.mlir 

%76 = "onnx.Concat"(%66, %75, %22, %24, %39, %41, %15, %17, %31, %33, %6, %57, %55, %53, %51, %49, %47) {axis = 33554432 : si64, onnx_node_name = "StatefulPartitionedCall/model_4/tf.concat_1/concat"} : (tensor<*xf32>, tensor<*xf32>, tensor<*xf32>, tensor<*xf32>, tensor<*xf32>, tensor<*xf32>, tensor<*xf32>, tensor<*xf32>, tensor<*xf32>, tensor<*xf32>, tensor<*xf32>, tensor<*xf32>, tensor<*xf32>, tensor<*xf32>, tensor<*xf32>, tensor<*xf32>, tensor<*xf32>) -> tensor<*xf32>
...
```    

According to the ONNX specification (https://github.com/onnx/onnx/blob/main/docs/Operators.md#Concat) the `axis` attribute is constrained to the range `[-r, r-1]` where r = rank(inputs). Although the rank of the input tensor is initially unknown, by the time the compiler performs shape inference on the Concat operator its input have rank == 3, for exampl consider the following input:

```
currentInput %66 = "onnx.UnsqueezeV11"(%65) {axes = [2], onnx_node_name = "StatefulPartitionedCall/model_4/tf.expand_dims_10/ExpandDims"} : (tensor<?x7xf32>) -> tensor<?x7x1xf32>
```

That is the reason for the assertion.

**Comment by AlexandreEichenberger** [comment] 2022-03-29 22:53
@cjvolzka  Ok, that appears to be a converter issue... I have seen that in the past also for others, sometime a neg number that is seen here as a large positive number. 

I quick fix is to emit the unoptimized MLIR file, fix the wrong value, and then finish the compilation and check that it work then.

@etiotto thanks for the quick turnaround on studying the cause of the error.

**Comment by tungld** [comment] 2022-03-30 02:35
Opened the model with netron and saw concat's axis is 33554432 as Ettore reported. It would be a converter issue.

I wonder why our verification of Concat did not catch this situation. It should be verification, not shape inference, to detect such an issue.

**Comment by AlexandreEichenberger** [comment] 2022-03-30 14:47
Agreed, but technically we need to know the rank of the inputs, which may only be avail after shape inference.
```
Attributes

axis : int (required)
Which axis to concat on. A negative value means counting dimensions from the back. Accepted range is [-r, r-1] where r = rank(inputs)..
```

though we could safely have a verifier error if the number is visibly out of bound, as we could safely assume that we could limit support to tensors of rank <100, for example.

**Comment by etiotto** [comment] 2022-03-30 18:26
PR #1291 is up for review. It addresses the case where the `rank` of certain operators is outside the range [-100,100].

**Comment by etiotto** [comment] 2022-03-30 21:17
@cjvolzka I am going to close this issue given we know the input model was invalid. To improve diagnostic I have opendd issue https://github.com/onnx/onnx-mlir/issues/1297, we will "attach" pull requests to implement that feature to that PR directly.

**Closed by etiotto** 2022-03-30 21:17 UTC
Labels: invalid, bug-to-track
