### ISSUE TITLE
mnist fails

### ISSUE THREAD

**Issue by tjingrant** [onnx/onnx-mlir#143] opened 2020-05-22 03:04 UTC
Hi @chentong319, 

Mnist model fails to compile after your commit is merged, could you take a look?
See the model attached.

Constant op now has wrong output type, for instance, try run with `-EmitONNXBasic` flag on the attached model, and you'll find:
```
    %7 = "onnx.Constant"() {value = dense<[-1, 9216]> : tensor<2xi64>} : () -> none
```

Tian.

Model file:
[mnist-simple.onnx.zip](https://github.com/onnx/onnx-mlir/files/4665862/mnist-simple.onnx.zip)

**Comment by chentong319** [comment] 2020-05-22 03:55
The cause is that the constantOP is special in type inference: it's output data type depends on attribute, not input argument.  I can add a special importer for ConstantOp to set the type correctly. 
Since that patch already merged, I will open another patch to fix this. It took me  lots of efforts to manually merge this patch with master.

**Comment by tjingrant** [comment] 2020-05-22 03:58
@chentong319 yeah, another patch to fix this issue will be nice.

I should've set up better testing infra to detect errors like this.

**Comment by chentong319** [comment] 2020-05-22 12:10
Can you send me some test case with ConstantOp in model? After I test with this patch, we can add them to backend test at least.

**Comment by tjingrant** [comment] 2020-05-22 12:13
@chentong319 the mnist one I uploaded is the only feasible one. The others are unfeasible to serve as test case now because our lack of support for handling large constants.

**Comment by tjingrant** [comment] 2020-05-22 13:15
@chentong319 for what is worth, you can somewhat easily test whether the model works using `util/debug.py` explained here: http://onnx.ai/onnx-mlir//DebuggingNumericalError.html.

**Closed** 2020-05-26 01:54 UTC
