### ISSUE TITLE
NNPA Leaky Relu test and reporting

### ISSUE THREAD

**Issue by AlexandreEichenberger** [onnx/onnx-mlir#1714] opened 2022-09-20 19:40 UTC
Handling for leaky relu was recently added for NNPA, but it is not being tested and/or reported in the `NNPA/backend/CMakeList.txt`

@imaihal or @negiyas: would you be able to add something like this but for leaky relate

```
    # ==OP== Relu
    # ==LIM== Input tensor must be less than or equal to 4 dimensions.
    test_relu_cpu,zdnn_relu
```

and rebuild the documentation using `make onnx_mlir_supported_ops_NNPA`

**Comment by negiyas** [comment] 2022-09-20 23:28
Thank you for the issue.

In the PR #1636,  standard backend tests are not used for testing the LeakyRelu on NNPA, but a special numerical test (TestLeakyReluNNPA) is used to test LeakyRelu with various arguments. 

To avoid performance regression by the PR, a single onnx.LeakyRelu is not executed on NNPA, and it is executed on NNPA only when the previous and following operations are executed on NNPA. Accordingly we need a special testing code to enable LeakyRelu on NNPA.

Of course it is possible to run all LeakyRelu on NNPA. Your comments about testing and conversion conditions are very welcome. Thank you.

```
def ReplaceONNXLeakyReluPattern: Pat<
  (ZHighStickOp (ONNXLeakyReluOp:$out (ZHighUnstickOp $X), $alpha),
                $layout),
  (ZHighSubOp
     (ZHighReluOp $X, (returnType $X)),
     (ZHighReluOp (ZHighMulOp $X,
                              (ZHighStickOp (GetMinusBcastConst $alpha,
                                             $out),
                                            $layout),
                              (returnType $X)),
                  (returnType $X))),
  [(IsStaticShapeTensor $X), (IsPlusConstantFloat $alpha)]
>;

```

**Comment by imaihal** [comment] 2022-09-21 01:24
@negiyas @AlexandreEichenberger 

> To avoid performance regression by the PR, a single onnx.LeakyRelu is not executed on NNPA, and it is executed on NNPA only when the previous and following operations are executed on NNPA. 

I think this can be written in the [document](https://github.com/onnx/onnx-mlir/blob/main/docs/SupportedONNXOps-NNPA.md) as limitation of LeakyRelu

For example,
```
   # ==OP== LeakyRelu
   # ==LIM== Run on NNPA when the previous and following operations are executed on NNPA
```

Backend test for leakyRelu can not be used, but I think we can add the sentence just for documentation(currently all of document for supported ops are written in the `NNPA/backend/CMakeList.txt`). I will update the document if this is ok.

**Comment by AlexandreEichenberger** [comment] 2022-09-21 13:16
Sure, if you don't feel like a test is appropriate/works, just add a PR to add the comments.

>    # ==LIM== Run on NNPA when the previous and following operations are executed on NNPA

I don't understand this. Maybe you can just say "Run on NNPA as a combination of Relu, multiply, and sub"

**Comment by imaihal** [comment] 2022-09-21 14:08
@AlexandreEichenberger

> To avoid performance regression by the PR, a single onnx.LeakyRelu is not executed on NNPA, and it is executed on NNPA only when the previous and following operations are executed on NNPA. 

As @negiyas wrote above,   
`zHigh op -> onnx.LeakyRelu -> zHigh op` is lowered to `zHigh op -> zHigh.Relu -> zHigh.Mul -> zHigh.Relu -> zHigh.Sub -> zHigh op`. However, `onnx op (CPU) -> onnx.LeakyRelu -> onnx op (CPU)`  is not lowered to zHigh.

Therefore, I wanted to describe that in `== LIM ==`. (previous and following operation means the operation before and after onnx.LeakyRelu)

**Comment by cjvolzka** [comment] 2022-09-21 15:09
@AlexandreEichenberger 
> I don't understand this. Maybe you can just say "Run on NNPA as a combination of Relu, multiply, and sub"

Would be a different comment. That would be commenting on how it's implemented. I can go both ways on if we include that level of detail in the doc.

> ==LIM== Run on NNPA when the previous and following operations are executed on NNPA

I believe what @imaihal is trying to convey is that the Op will only go to the NNPA if the Op immediately before it and the Op immediately after it are also NNPA Ops. If that's not true, the Op will use the CPU version of LeakyRelu instead. 

The wording is open to debate, but I think that's an important note to make in the doc. That way users can understand why sometimes the compiler uses onnx.LeakyRelu and other times uses zhigh.LeakyRelu (or whatever the dialect names might be) and a clue as to what they can do to make use NNPA version.

**Comment by AlexandreEichenberger** [comment] 2022-09-21 18:43
got it.

**Comment by AlexandreEichenberger** [comment] 2022-09-28 18:14
@negiyas if you have completed the work, please close this issue, thanks

**Comment by imaihal** [comment] 2022-10-18 02:38
Close this issue since https://github.com/onnx/onnx-mlir/pull/1786 was merged.

**Closed by imaihal** 2022-10-18 02:38 UTC
