### ISSUE TITLE
yolov3 models fail to compile on NNPA

### ISSUE THREAD

**Issue by Kadaeux** [onnx/onnx-mlir#2850] opened 2024-06-17 14:24 UTC
Compiling the  yolov3-10, yolov3-12, and tiny-yolov3-11 models for NNPA produces errors around invalid Tensor rank. The models compile fine for CPU. This issue does not appear to exist on earlier opset versions. The error is the same for all three models.

```
The ONNX model has 61953242 elements in its initializers. This value would be close to and greater than the number of parameters in the model. Because there is no way to exactly count the number of parameters, this value can be used to have a rough idea of the number of parameters in the model.
Could not get layout by rank. Rank must be 1, 2, 3, or 4
UNREACHABLE executed at src/Accelerators/NNPA/Dialect/ZHigh/ZHighOps/OpHelper.cpp:86!
Aborted (core dumped)
```

## Reproduce

I acquired the onnx models directly from the public onnx repository.

- (YOLOv3) https://github.com/onnx/models/tree/main/validated/vision/object_detection_segmentation/yolov3
- (Tiny YOLOv3) https://github.com/onnx/models/tree/main/validated/vision/object_detection_segmentation/tiny-yolov3

### Compilation

I tested compilation with the following flags
`-v -O3 --mcpu=z16 --mtriple=s390x-ibm-loz --EmitLib --maccel=NNPA --onnx-op-stats`

**Comment by hamptonm1** [comment] 2024-06-21 19:06
```
root@791403fb8c48:/workdir/onnx-mlir/build# ONNX_MLIR_HOME=/workdir/onnx-mlir/build/Debug python3 ../utils/RunONNXModel.py -m=tiny-yolov3-11.onnx -c="-O3 -mcpu=z16 --maccel=NNPA" --shape-info="0:1x1" --save-so=./model-z16.so
Temporary directory has been created at /tmp/tmp7utopgz1
Compiling the model ...
%134 = "onnx.Cast"(%133) {onnx_node_name = "TFNodes/yolo_evaluation_layer_1/Cast_3", saturate = 1 : si64, to = f32} : (tensor<2xi32>) -> tensor<2xf32>
%108 = "onnx.Squeeze"(%arg1, %33) {onnx_node_name = "TFNodes/yolo_evaluation_layer_1/Squeeze_36"} : (tensor<?x2xf32>, tensor<1xi64>) -> tensor<2xf32>
%134 = "onnx.Cast"(%133) {onnx_node_name = "TFNodes/yolo_evaluation_layer_1/Cast_3", saturate = 1 : si64, to = f32} : (tensor<2xi32>) -> tensor<2xf32>
%142 = "onnx.Round"(%141) {onnx_node_name = "TFNodes/yolo_evaluation_layer_1/Round"} : (tensor<2xf32>) -> tensor<2xf32>
%147 = "onnx.Sub"(%134, %142) {device = "nnpa", onnx_node_name = "TFNodes/yolo_evaluation_layer_1/sub"} : (tensor<2xf32>, tensor<2xf32>) -> tensor<2xf32>
%0 = onnx.Constant dense<2.000000e+00> : tensor<2xf32>
%152 = "onnx.Div"(%147, %0) : (tensor<2xf32>, tensor<2xf32>) -> tensor<2xf32>
%134 = "onnx.Cast"(%133) {onnx_node_name = "TFNodes/yolo_evaluation_layer_1/Cast_3", saturate = 1 : si64, to = f32} : (tensor<2xi32>) -> tensor<2xf32>
%134 = "onnx.Cast"(%133) {onnx_node_name = "TFNodes/yolo_evaluation_layer_1/Cast_3", saturate = 1 : si64, to = f32} : (tensor<2xi32>) -> tensor<2xf32>
%142 = "onnx.Round"(%141) {onnx_node_name = "TFNodes/yolo_evaluation_layer_1/Round"} : (tensor<2xf32>) -> tensor<2xf32>
%163 = "onnx.Cast"(%133) {onnx_node_name = "TFNodes/yolo_evaluation_layer_1/Cast_7", saturate = 1 : si64, to = f32} : (tensor<2xi32>) -> tensor<2xf32>
%108 = "onnx.Squeeze"(%arg1, %33) {onnx_node_name = "TFNodes/yolo_evaluation_layer_1/Squeeze_36"} : (tensor<?x2xf32>, tensor<1xi64>) -> tensor<2xf32>
%163 = "onnx.Cast"(%133) {onnx_node_name = "TFNodes/yolo_evaluation_layer_1/Cast_7", saturate = 1 : si64, to = f32} : (tensor<2xi32>) -> tensor<2xf32>
%171 = "onnx.Round"(%170) {onnx_node_name = "TFNodes/yolo_evaluation_layer_1/Round_1"} : (tensor<2xf32>) -> tensor<2xf32>
%176 = "onnx.Sub"(%163, %171) {device = "nnpa", onnx_node_name = "TFNodes/yolo_evaluation_layer_1/sub_3"} : (tensor<2xf32>, tensor<2xf32>) -> tensor<2xf32>
%0 = onnx.Constant dense<2.000000e+00> : tensor<2xf32>
%181 = "onnx.Div"(%176, %0) : (tensor<2xf32>, tensor<2xf32>) -> tensor<2xf32>
%163 = "onnx.Cast"(%133) {onnx_node_name = "TFNodes/yolo_evaluation_layer_1/Cast_7", saturate = 1 : si64, to = f32} : (tensor<2xi32>) -> tensor<2xf32>
%163 = "onnx.Cast"(%133) {onnx_node_name = "TFNodes/yolo_evaluation_layer_1/Cast_7", saturate = 1 : si64, to = f32} : (tensor<2xi32>) -> tensor<2xf32>
%171 = "onnx.Round"(%170) {onnx_node_name = "TFNodes/yolo_evaluation_layer_1/Round_1"} : (tensor<2xf32>) -> tensor<2xf32>
%224 = "onnx.Slice"(%223, %40, %39, %39, %6) {onnx_node_name = "TFNodes/yolo_evaluation_layer_1/strided_slice_10"} : (tensor<?x?x?x3x85xf32>, tensor<1xi64>, tensor<1xi64>, tensor<1xi64>, tensor<1xi64>) -> tensor<?x?x?x3x2xf32>
The rank is: 5
Could not get layout by rank. Rank must be 1, 2, 3, or 4
UNREACHABLE executed at /workdir/onnx-mlir/src/Accelerators/NNPA/Dialect/ZHigh/ZHighOps/OpHelper.cpp:87!
```

**Comment by hamptonm1** [comment] 2024-06-26 02:25
I got the model to compile when I move to an older version of LLVM and StableHLO( LLVM to 7ac7d418ac2b16fd44789dcf48e2b5d73de3e715 and StableHLO to 2a0595b). I also moved to an older version of ONNX-MLIR (35f66a01):

```
root@791403fb8c48:/workdir/onnx-mlir/build#  ./Debug/bin/onnx-mlir --O3 --EmitLib --mtriple=s390x-ibm-loz --mcpu=z16 --maccel=NNPA --onnx-op-stats TXT tiny-yolov3-11.onnx -v
Onnx-mlir command: ./Debug/bin/onnx-mlir --O3 --EmitLib --mtriple=s390x-ibm-loz --mcpu=z16 --maccel=NNPA --onnx-op-stats TXT tiny-yolov3-11.onnx -v
The ONNX model has 8858988 elements in its initializers. This value would be close to and greater than the number of parameters in the model. Because there is no way to exactly count the number of parameters, this value can be used to have a rough idea of the number of parameters in the model.
Operations encountered:
-----------------------
   func.func               , 1
   func.return             , 1
   onnx.Add                , 8
   onnx.Cast               , 40
   onnx.Ceil               , 4
   onnx.Concat             , 20
   onnx.Constant           , 54
   onnx.Conv               , 13
   onnx.Dim                , 9
   onnx.Div                , 8
   onnx.Exp                , 2
   onnx.LeakyRelu          , 11
   onnx.Loop               , 4
   onnx.Mul                , 13
   onnx.NoValue            , 1
   onnx.NonMaxSuppression  , 1
   onnx.ReduceMinV13       , 2
   onnx.Reshape            , 10
   onnx.Resize             , 1
   onnx.Round              , 2
   onnx.Sigmoid            , 6
   onnx.Slice              , 33
   onnx.Squeeze            , 5
   onnx.Sub                , 4
   onnx.Tile               , 4
   onnx.Transpose          , 3
   onnx.Unsqueeze          , 3
   onnx.Yield              , 4
  zhigh.Div                , 8
  zhigh.MaxPool2D          , 6
  zhigh.Stick              , 11
  zhigh.StickifiedConstant , 2
  zhigh.Sub                , 2
  zhigh.Unstick            , 12
[/workdir/onnx-mlir/build/] /workdir/llvm-project/build/bin/opt: opt -O3 --mtriple=s390x-ibm-loz --mcpu=z16 --code-model small -o tiny-yolov3-11.bc tiny-yolov3-11.unoptimized.bc
[/workdir/onnx-mlir/build/] /workdir/llvm-project/build/bin/llc: llc -O3 --mtriple=s390x-ibm-loz --mcpu=z16 --code-model small -filetype=obj -relocation-model=pic -o tiny-yolov3-11.o tiny-yolov3-11.bc
[/workdir/onnx-mlir/build/] /usr/bin/c++: c++ tiny-yolov3-11.o -o tiny-yolov3-11.so -shared -fPIC -L/workdir/onnx-mlir/build/Debug/lib -lRuntimeNNPA -lzdnn -lcruntime
Shared library 'tiny-yolov3-11.so' has been compiled.
root@791403fb8c48:/workdir/onnx-mlir/build# 
```

So the Rank is actual 1 before the LLVM changes...
**The Rank is:1**

**Comment by hamptonm1** [comment] 2024-06-26 16:24
After more testing, I found the offending commit [cf651e7](https://github.com/onnx/onnx-mlir/commit/cf651e75ba88e391b786b9c7e7009d6efcd02c49) which has to do with the update for the `NNPA` flag which would make sense why this maybe causing an issue. It has nothing to do with `LLVM` or `Stablehlo` upgrade.

**Comment by AlexandreEichenberger** [comment] 2024-06-26 18:26
@imaihal Do you mind to look into this? @hamptonm1 believes that a commit associated with #2819 may be the cause of this regression.

Thanks @hamptonm1 for looking into this in such details.

**Comment by hamptonm1** [comment] 2024-06-26 19:58
@imaihal @AlexandreEichenberger I think I have the fix actually! Will create a PR in a few minutes :)

**Comment by hamptonm1** [comment] 2024-06-27 02:34
@Kadaeux  The fix is merged in…. You can test yourself before closing out.

**Closed** 2024-06-27 13:09 UTC

**Comment by AlexandreEichenberger** [comment] 2024-06-27 15:34
Thanks to both of you.
